# Generated by Django 5.2 for the initial Restaurant model.

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="店名")),
                ("description", models.TextField(verbose_name="説明")),
                ("address", models.CharField(max_length=255, verbose_name="住所")),
                ("business_hours", models.TextField(verbose_name="営業時間")),
            ],
            options={
                "verbose_name": "店舗",
                "verbose_name_plural": "店舗",
                "ordering": ["pk"],
            },
        ),
    ]
