# Generated by Django 5.2.17 on 2026-10-02 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='閉店時刻'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='last_reservation_time',
            field=models.TimeField(blank=True, help_text='この時刻ちょうどの予約も可能です。開店より後、閉店より前に設定してください。', null=True, verbose_name='最終予約可能時刻'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_party_size',
            field=models.PositiveSmallIntegerField(default=10, help_text='1予約あたりの最大人数です。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)], verbose_name='最大予約人数'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='日本時間・分単位。時刻3項目が未設定の場合は予約受付を停止します。', null=True, verbose_name='開店時刻'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='party_size',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_hours',
            field=models.TextField(help_text='L.O.などの案内文です。予約可否の判定には使用しません。', verbose_name='営業時間の補足案内'),
        ),
    ]
